FROM mongo:latest
EXPOSE 27017

# Set environment variables (optional, adjust as needed)
# ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=admin-password

# COPY ./mongo-init-scripts/ /docker-entrypoint-initdb.d/
CMD ["mongod"]